name: assignment_monika
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter_bloc: ^8.1.2
  loading_indicator: ^3.1.0
  bloc_test: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.1.7
  mockito: 5.2.0

flutter:
  uses-material-design: true
